version: "3.1"

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: Omega123
      WORDPRESS_DB_NAME: wordpress-db
    volumes:
      - ./wordpress:/var/www/html

  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress-db
      MYSQL_USER: user
      MYSQL_PASSWORD: Omega123
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - ./database:/var/lib/mysql